# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Ir"
weight = 1

[id]
languageName = "study"
languagedirection = "ltr"
title = "st-Ir"
weight = 2
url = "/id"


[ar]
languageName = "عربي"
languagedirection = "rtl"
title = "موقع تجريبي"
weight = 3
