# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Ir"
weight = 1

[study]
languageName = "Indo"
languagedirection = "ltr"
title = "st-Ir"
weight = 2


[ar]
languageName = "عربي"
languagedirection = "rtl"
title = "موقع تجريبي"
weight = 3
