# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Hobbies"
weight = 1

[id]
languageName = "id"
languagedirection = "ltr"
title = "st-Ir"
weight = 2

[ar]
languageName = "عربي"
languagedirection = "rtl"
title = "موقع تجريبي"
weight = 3
